version: '3'

services:

  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "control_vehicles"
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - mysql-compose-network

  app:
    build:
      context: ./
    image: WebCarHSJ:v1
    container_name: WebCarHSJ
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - ./:/var/www
    networks:
      - mysql-compose-network  

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on: 
      - mysqlsrv
    networks:
      - mysql-compose-network    

networks: 
  mysql-compose-network:
    driver: bridge

volumes:  
  mysqldata: 
